services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python3 -m start
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
